
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# No redirects for /api/*, Astro Netlify adapter maneja las serverless

[build.environment]
  NODE_VERSION = "18"
