name: Update YouTube Videos
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar videos
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          curl -v -X POST \
            -H "Authorization: Bearer $CRON_SECRET" \
            https://recopilaciones.jonastown.es/api/update-videos