name: Update YouTube Videos
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Update Videos from YouTube
        run: |
          response=$(curl -s -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            "${{ secrets.SITE_URL }}/api/update-videos")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Videos updated successfully"
            echo "$body"
          else
            echo "❌ Failed to update videos (HTTP $http_code)"
            echo "$body"
            exit 1
          fi
